#!/bin/bash
echo "========================================="
echo "  Slate Demo Presentation"
echo "========================================="
echo ""
echo "Created: demo-presentation.md"
echo "Slides: 13"
echo "Lines: 182"
echo ""
echo "To view the presentation interactively:"
echo ""
echo "  ./slate present demo-presentation.md"
echo ""
echo "Navigation:"
echo "  →, L  - Next slide"
echo "  ←, H         - Previous slide"
echo "  Home, G      - First slide"
echo "  End, Shift+G - Last slide"
echo "  ?            - Show help"
echo "  Q, Esc       - Quit"
echo ""
echo "========================================="
echo ""
echo "Starting presentation in 2 seconds..."
sleep 2
./bin/slate-darwin-arm64 present demo-presentation.md
